# Autogenerated wrapper script for LLVM_utils_unified_jll for armv7l-linux-gnueabihf-cxx11-llvm_version+18
export llc, lli, lli_child_target, llvm_FileCheck, llvm_PerfectShuffle, llvm_UnicodeNameMappingGenerator, llvm_addr2line, llvm_amdgpu_arch, llvm_ar, llvm_as, llvm_bcanalyzer, llvm_bitcode_strip, llvm_bugpoint, llvm_c_test, llvm_cat, llvm_cfi_verify, llvm_count, llvm_cov, llvm_cvtres, llvm_cxxdump, llvm_cxxfilt, llvm_cxxmap, llvm_debuginfo_analyzer, llvm_debuginfod, llvm_debuginfod_find, llvm_diagtool, llvm_diff, llvm_dis, llvm_dlltool, llvm_dwarfdump, llvm_dwarfutil, llvm_dwp, llvm_extract, llvm_find_all_symbols, llvm_gsymutil, llvm_ifs, llvm_install_name_tool, llvm_jitlink, llvm_jitlink_executor, llvm_lib, llvm_libtool_darwin, llvm_link, llvm_lipo, llvm_lto, llvm_lto2, llvm_mc, llvm_mca, llvm_ml, llvm_modextract, llvm_modularize, llvm_mt, llvm_nm, llvm_not, llvm_nvptx_arch, llvm_obj2yaml, llvm_objcopy, llvm_objdump, llvm_opt_report, llvm_otool, llvm_pdbutil, llvm_pp_trace, llvm_profdata, llvm_profgen, llvm_ranlib, llvm_rc, llvm_readelf, llvm_readobj, llvm_readtapi, llvm_reduce, llvm_remarkutil, llvm_rtdyld, llvm_sancov, llvm_sanstats, llvm_sim, llvm_size, llvm_split, llvm_split_file, llvm_stress, llvm_strings, llvm_strip, llvm_symbolizer, llvm_tblgen, llvm_tli_checker, llvm_undname, llvm_verify_uselistorder, llvm_windres, llvm_xray, llvm_yaml2obj, llvm_yaml_bench, opt

using Zlib_jll
using libLLVM_jll
JLLWrappers.@generate_wrapper_header("LLVM_utils_unified")
JLLWrappers.@declare_executable_product(llc)
JLLWrappers.@declare_executable_product(lli)
JLLWrappers.@declare_executable_product(lli_child_target)
JLLWrappers.@declare_executable_product(llvm_FileCheck)
JLLWrappers.@declare_executable_product(llvm_PerfectShuffle)
JLLWrappers.@declare_executable_product(llvm_UnicodeNameMappingGenerator)
JLLWrappers.@declare_executable_product(llvm_addr2line)
JLLWrappers.@declare_executable_product(llvm_amdgpu_arch)
JLLWrappers.@declare_executable_product(llvm_ar)
JLLWrappers.@declare_executable_product(llvm_as)
JLLWrappers.@declare_executable_product(llvm_bcanalyzer)
JLLWrappers.@declare_executable_product(llvm_bitcode_strip)
JLLWrappers.@declare_executable_product(llvm_bugpoint)
JLLWrappers.@declare_executable_product(llvm_c_test)
JLLWrappers.@declare_executable_product(llvm_cat)
JLLWrappers.@declare_executable_product(llvm_cfi_verify)
JLLWrappers.@declare_executable_product(llvm_count)
JLLWrappers.@declare_executable_product(llvm_cov)
JLLWrappers.@declare_executable_product(llvm_cvtres)
JLLWrappers.@declare_executable_product(llvm_cxxdump)
JLLWrappers.@declare_executable_product(llvm_cxxfilt)
JLLWrappers.@declare_executable_product(llvm_cxxmap)
JLLWrappers.@declare_executable_product(llvm_debuginfo_analyzer)
JLLWrappers.@declare_executable_product(llvm_debuginfod)
JLLWrappers.@declare_executable_product(llvm_debuginfod_find)
JLLWrappers.@declare_executable_product(llvm_diagtool)
JLLWrappers.@declare_executable_product(llvm_diff)
JLLWrappers.@declare_executable_product(llvm_dis)
JLLWrappers.@declare_executable_product(llvm_dlltool)
JLLWrappers.@declare_executable_product(llvm_dwarfdump)
JLLWrappers.@declare_executable_product(llvm_dwarfutil)
JLLWrappers.@declare_executable_product(llvm_dwp)
JLLWrappers.@declare_executable_product(llvm_extract)
JLLWrappers.@declare_executable_product(llvm_find_all_symbols)
JLLWrappers.@declare_executable_product(llvm_gsymutil)
JLLWrappers.@declare_executable_product(llvm_ifs)
JLLWrappers.@declare_executable_product(llvm_install_name_tool)
JLLWrappers.@declare_executable_product(llvm_jitlink)
JLLWrappers.@declare_executable_product(llvm_jitlink_executor)
JLLWrappers.@declare_executable_product(llvm_lib)
JLLWrappers.@declare_executable_product(llvm_libtool_darwin)
JLLWrappers.@declare_executable_product(llvm_link)
JLLWrappers.@declare_executable_product(llvm_lipo)
JLLWrappers.@declare_executable_product(llvm_lto)
JLLWrappers.@declare_executable_product(llvm_lto2)
JLLWrappers.@declare_executable_product(llvm_mc)
JLLWrappers.@declare_executable_product(llvm_mca)
JLLWrappers.@declare_executable_product(llvm_ml)
JLLWrappers.@declare_executable_product(llvm_modextract)
JLLWrappers.@declare_executable_product(llvm_modularize)
JLLWrappers.@declare_executable_product(llvm_mt)
JLLWrappers.@declare_executable_product(llvm_nm)
JLLWrappers.@declare_executable_product(llvm_not)
JLLWrappers.@declare_executable_product(llvm_nvptx_arch)
JLLWrappers.@declare_executable_product(llvm_obj2yaml)
JLLWrappers.@declare_executable_product(llvm_objcopy)
JLLWrappers.@declare_executable_product(llvm_objdump)
JLLWrappers.@declare_executable_product(llvm_opt_report)
JLLWrappers.@declare_executable_product(llvm_otool)
JLLWrappers.@declare_executable_product(llvm_pdbutil)
JLLWrappers.@declare_executable_product(llvm_pp_trace)
JLLWrappers.@declare_executable_product(llvm_profdata)
JLLWrappers.@declare_executable_product(llvm_profgen)
JLLWrappers.@declare_executable_product(llvm_ranlib)
JLLWrappers.@declare_executable_product(llvm_rc)
JLLWrappers.@declare_executable_product(llvm_readelf)
JLLWrappers.@declare_executable_product(llvm_readobj)
JLLWrappers.@declare_executable_product(llvm_readtapi)
JLLWrappers.@declare_executable_product(llvm_reduce)
JLLWrappers.@declare_executable_product(llvm_remarkutil)
JLLWrappers.@declare_executable_product(llvm_rtdyld)
JLLWrappers.@declare_executable_product(llvm_sancov)
JLLWrappers.@declare_executable_product(llvm_sanstats)
JLLWrappers.@declare_executable_product(llvm_sim)
JLLWrappers.@declare_executable_product(llvm_size)
JLLWrappers.@declare_executable_product(llvm_split)
JLLWrappers.@declare_executable_product(llvm_split_file)
JLLWrappers.@declare_executable_product(llvm_stress)
JLLWrappers.@declare_executable_product(llvm_strings)
JLLWrappers.@declare_executable_product(llvm_strip)
JLLWrappers.@declare_executable_product(llvm_symbolizer)
JLLWrappers.@declare_executable_product(llvm_tblgen)
JLLWrappers.@declare_executable_product(llvm_tli_checker)
JLLWrappers.@declare_executable_product(llvm_undname)
JLLWrappers.@declare_executable_product(llvm_verify_uselistorder)
JLLWrappers.@declare_executable_product(llvm_windres)
JLLWrappers.@declare_executable_product(llvm_xray)
JLLWrappers.@declare_executable_product(llvm_yaml2obj)
JLLWrappers.@declare_executable_product(llvm_yaml_bench)
JLLWrappers.@declare_executable_product(opt)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, libLLVM_jll)
    JLLWrappers.@init_executable_product(
        llc,
        "tools/llc",
    )

    JLLWrappers.@init_executable_product(
        lli,
        "tools/lli",
    )

    JLLWrappers.@init_executable_product(
        lli_child_target,
        "tools/lli-child-target",
    )

    JLLWrappers.@init_executable_product(
        llvm_FileCheck,
        "tools/FileCheck",
    )

    JLLWrappers.@init_executable_product(
        llvm_PerfectShuffle,
        "tools/llvm-PerfectShuffle",
    )

    JLLWrappers.@init_executable_product(
        llvm_UnicodeNameMappingGenerator,
        "tools/UnicodeNameMappingGenerator",
    )

    JLLWrappers.@init_executable_product(
        llvm_addr2line,
        "tools/llvm-addr2line",
    )

    JLLWrappers.@init_executable_product(
        llvm_amdgpu_arch,
        "tools/amdgpu-arch",
    )

    JLLWrappers.@init_executable_product(
        llvm_ar,
        "tools/llvm-ar",
    )

    JLLWrappers.@init_executable_product(
        llvm_as,
        "tools/llvm-as",
    )

    JLLWrappers.@init_executable_product(
        llvm_bcanalyzer,
        "tools/llvm-bcanalyzer",
    )

    JLLWrappers.@init_executable_product(
        llvm_bitcode_strip,
        "tools/llvm-bitcode-strip",
    )

    JLLWrappers.@init_executable_product(
        llvm_bugpoint,
        "tools/bugpoint",
    )

    JLLWrappers.@init_executable_product(
        llvm_c_test,
        "tools/llvm-c-test",
    )

    JLLWrappers.@init_executable_product(
        llvm_cat,
        "tools/llvm-cat",
    )

    JLLWrappers.@init_executable_product(
        llvm_cfi_verify,
        "tools/llvm-cfi-verify",
    )

    JLLWrappers.@init_executable_product(
        llvm_count,
        "tools/count",
    )

    JLLWrappers.@init_executable_product(
        llvm_cov,
        "tools/llvm-cov",
    )

    JLLWrappers.@init_executable_product(
        llvm_cvtres,
        "tools/llvm-cvtres",
    )

    JLLWrappers.@init_executable_product(
        llvm_cxxdump,
        "tools/llvm-cxxdump",
    )

    JLLWrappers.@init_executable_product(
        llvm_cxxfilt,
        "tools/llvm-cxxfilt",
    )

    JLLWrappers.@init_executable_product(
        llvm_cxxmap,
        "tools/llvm-cxxmap",
    )

    JLLWrappers.@init_executable_product(
        llvm_debuginfo_analyzer,
        "tools/llvm-debuginfo-analyzer",
    )

    JLLWrappers.@init_executable_product(
        llvm_debuginfod,
        "tools/llvm-debuginfod",
    )

    JLLWrappers.@init_executable_product(
        llvm_debuginfod_find,
        "tools/llvm-debuginfod-find",
    )

    JLLWrappers.@init_executable_product(
        llvm_diagtool,
        "tools/diagtool",
    )

    JLLWrappers.@init_executable_product(
        llvm_diff,
        "tools/llvm-diff",
    )

    JLLWrappers.@init_executable_product(
        llvm_dis,
        "tools/llvm-dis",
    )

    JLLWrappers.@init_executable_product(
        llvm_dlltool,
        "tools/llvm-dlltool",
    )

    JLLWrappers.@init_executable_product(
        llvm_dwarfdump,
        "tools/llvm-dwarfdump",
    )

    JLLWrappers.@init_executable_product(
        llvm_dwarfutil,
        "tools/llvm-dwarfutil",
    )

    JLLWrappers.@init_executable_product(
        llvm_dwp,
        "tools/llvm-dwp",
    )

    JLLWrappers.@init_executable_product(
        llvm_extract,
        "tools/llvm-extract",
    )

    JLLWrappers.@init_executable_product(
        llvm_find_all_symbols,
        "tools/find-all-symbols",
    )

    JLLWrappers.@init_executable_product(
        llvm_gsymutil,
        "tools/llvm-gsymutil",
    )

    JLLWrappers.@init_executable_product(
        llvm_ifs,
        "tools/llvm-ifs",
    )

    JLLWrappers.@init_executable_product(
        llvm_install_name_tool,
        "tools/llvm-install-name-tool",
    )

    JLLWrappers.@init_executable_product(
        llvm_jitlink,
        "tools/llvm-jitlink",
    )

    JLLWrappers.@init_executable_product(
        llvm_jitlink_executor,
        "tools/llvm-jitlink-executor",
    )

    JLLWrappers.@init_executable_product(
        llvm_lib,
        "tools/llvm-lib",
    )

    JLLWrappers.@init_executable_product(
        llvm_libtool_darwin,
        "tools/llvm-libtool-darwin",
    )

    JLLWrappers.@init_executable_product(
        llvm_link,
        "tools/llvm-link",
    )

    JLLWrappers.@init_executable_product(
        llvm_lipo,
        "tools/llvm-lipo",
    )

    JLLWrappers.@init_executable_product(
        llvm_lto,
        "tools/llvm-lto",
    )

    JLLWrappers.@init_executable_product(
        llvm_lto2,
        "tools/llvm-lto2",
    )

    JLLWrappers.@init_executable_product(
        llvm_mc,
        "tools/llvm-mc",
    )

    JLLWrappers.@init_executable_product(
        llvm_mca,
        "tools/llvm-mca",
    )

    JLLWrappers.@init_executable_product(
        llvm_ml,
        "tools/llvm-ml",
    )

    JLLWrappers.@init_executable_product(
        llvm_modextract,
        "tools/llvm-modextract",
    )

    JLLWrappers.@init_executable_product(
        llvm_modularize,
        "tools/modularize",
    )

    JLLWrappers.@init_executable_product(
        llvm_mt,
        "tools/llvm-mt",
    )

    JLLWrappers.@init_executable_product(
        llvm_nm,
        "tools/llvm-nm",
    )

    JLLWrappers.@init_executable_product(
        llvm_not,
        "tools/not",
    )

    JLLWrappers.@init_executable_product(
        llvm_nvptx_arch,
        "tools/nvptx-arch",
    )

    JLLWrappers.@init_executable_product(
        llvm_obj2yaml,
        "tools/obj2yaml",
    )

    JLLWrappers.@init_executable_product(
        llvm_objcopy,
        "tools/llvm-objcopy",
    )

    JLLWrappers.@init_executable_product(
        llvm_objdump,
        "tools/llvm-objdump",
    )

    JLLWrappers.@init_executable_product(
        llvm_opt_report,
        "tools/llvm-opt-report",
    )

    JLLWrappers.@init_executable_product(
        llvm_otool,
        "tools/llvm-otool",
    )

    JLLWrappers.@init_executable_product(
        llvm_pdbutil,
        "tools/llvm-pdbutil",
    )

    JLLWrappers.@init_executable_product(
        llvm_pp_trace,
        "tools/pp-trace",
    )

    JLLWrappers.@init_executable_product(
        llvm_profdata,
        "tools/llvm-profdata",
    )

    JLLWrappers.@init_executable_product(
        llvm_profgen,
        "tools/llvm-profgen",
    )

    JLLWrappers.@init_executable_product(
        llvm_ranlib,
        "tools/llvm-ranlib",
    )

    JLLWrappers.@init_executable_product(
        llvm_rc,
        "tools/llvm-rc",
    )

    JLLWrappers.@init_executable_product(
        llvm_readelf,
        "tools/llvm-readelf",
    )

    JLLWrappers.@init_executable_product(
        llvm_readobj,
        "tools/llvm-readobj",
    )

    JLLWrappers.@init_executable_product(
        llvm_readtapi,
        "tools/llvm-readtapi",
    )

    JLLWrappers.@init_executable_product(
        llvm_reduce,
        "tools/llvm-reduce",
    )

    JLLWrappers.@init_executable_product(
        llvm_remarkutil,
        "tools/llvm-remarkutil",
    )

    JLLWrappers.@init_executable_product(
        llvm_rtdyld,
        "tools/llvm-rtdyld",
    )

    JLLWrappers.@init_executable_product(
        llvm_sancov,
        "tools/sancov",
    )

    JLLWrappers.@init_executable_product(
        llvm_sanstats,
        "tools/sanstats",
    )

    JLLWrappers.@init_executable_product(
        llvm_sim,
        "tools/llvm-sim",
    )

    JLLWrappers.@init_executable_product(
        llvm_size,
        "tools/llvm-size",
    )

    JLLWrappers.@init_executable_product(
        llvm_split,
        "tools/llvm-split",
    )

    JLLWrappers.@init_executable_product(
        llvm_split_file,
        "tools/split-file",
    )

    JLLWrappers.@init_executable_product(
        llvm_stress,
        "tools/llvm-stress",
    )

    JLLWrappers.@init_executable_product(
        llvm_strings,
        "tools/llvm-strings",
    )

    JLLWrappers.@init_executable_product(
        llvm_strip,
        "tools/llvm-strip",
    )

    JLLWrappers.@init_executable_product(
        llvm_symbolizer,
        "tools/llvm-symbolizer",
    )

    JLLWrappers.@init_executable_product(
        llvm_tblgen,
        "tools/llvm-tblgen",
    )

    JLLWrappers.@init_executable_product(
        llvm_tli_checker,
        "tools/llvm-tli-checker",
    )

    JLLWrappers.@init_executable_product(
        llvm_undname,
        "tools/llvm-undname",
    )

    JLLWrappers.@init_executable_product(
        llvm_verify_uselistorder,
        "tools/verify-uselistorder",
    )

    JLLWrappers.@init_executable_product(
        llvm_windres,
        "tools/llvm-windres",
    )

    JLLWrappers.@init_executable_product(
        llvm_xray,
        "tools/llvm-xray",
    )

    JLLWrappers.@init_executable_product(
        llvm_yaml2obj,
        "tools/yaml2obj",
    )

    JLLWrappers.@init_executable_product(
        llvm_yaml_bench,
        "tools/yaml-bench",
    )

    JLLWrappers.@init_executable_product(
        opt,
        "tools/opt",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
