# Autogenerated wrapper script for LLVM_utils_unified_jll for i686-w64-mingw32-cxx11-llvm_version+18.asserts
export llc, lli, lli_child_target, llvm_FileCheck, llvm_PerfectShuffle, llvm_UnicodeNameMappingGenerator, llvm_addr2line, llvm_amdgpu_arch, llvm_ar, llvm_as, llvm_bcanalyzer, llvm_bitcode_strip, llvm_bugpoint, llvm_c_test, llvm_cat, llvm_cfi_verify, llvm_count, llvm_cov, llvm_cvtres, llvm_cxxdump, llvm_cxxfilt, llvm_cxxmap, llvm_debuginfo_analyzer, llvm_debuginfod, llvm_debuginfod_find, llvm_diagtool, llvm_diff, llvm_dis, llvm_dlltool, llvm_dwarfdump, llvm_dwarfutil, llvm_dwp, llvm_extract, llvm_find_all_symbols, llvm_gsymutil, llvm_ifs, llvm_install_name_tool, llvm_jitlink, llvm_jitlink_executor, llvm_lib, llvm_libtool_darwin, llvm_link, llvm_lipo, llvm_lto, llvm_lto2, llvm_mc, llvm_mca, llvm_ml, llvm_modextract, llvm_modularize, llvm_mt, llvm_nm, llvm_not, llvm_nvptx_arch, llvm_obj2yaml, llvm_objcopy, llvm_objdump, llvm_opt_report, llvm_otool, llvm_pdbutil, llvm_pp_trace, llvm_profdata, llvm_profgen, llvm_ranlib, llvm_rc, llvm_readelf, llvm_readobj, llvm_readtapi, llvm_reduce, llvm_remarkutil, llvm_rtdyld, llvm_sancov, llvm_sanstats, llvm_sim, llvm_size, llvm_split, llvm_split_file, llvm_stress, llvm_strings, llvm_strip, llvm_symbolizer, llvm_tblgen, llvm_tli_checker, llvm_undname, llvm_verify_uselistorder, llvm_windres, llvm_xray, llvm_yaml2obj, llvm_yaml_bench, opt

using Zlib_jll
using libLLVM_jll
JLLWrappers.@generate_wrapper_header("LLVM_utils_unified")
JLLWrappers.@declare_executable_product(llc)
JLLWrappers.@declare_executable_product(lli)
JLLWrappers.@declare_executable_product(lli_child_target)
JLLWrappers.@declare_executable_product(llvm_FileCheck)
JLLWrappers.@declare_executable_product(llvm_PerfectShuffle)
JLLWrappers.@declare_executable_product(llvm_UnicodeNameMappingGenerator)
JLLWrappers.@declare_executable_product(llvm_addr2line)
JLLWrappers.@declare_executable_product(llvm_amdgpu_arch)
JLLWrappers.@declare_executable_product(llvm_ar)
JLLWrappers.@declare_executable_product(llvm_as)
JLLWrappers.@declare_executable_product(llvm_bcanalyzer)
JLLWrappers.@declare_executable_product(llvm_bitcode_strip)
JLLWrappers.@declare_executable_product(llvm_bugpoint)
JLLWrappers.@declare_executable_product(llvm_c_test)
JLLWrappers.@declare_executable_product(llvm_cat)
JLLWrappers.@declare_executable_product(llvm_cfi_verify)
JLLWrappers.@declare_executable_product(llvm_count)
JLLWrappers.@declare_executable_product(llvm_cov)
JLLWrappers.@declare_executable_product(llvm_cvtres)
JLLWrappers.@declare_executable_product(llvm_cxxdump)
JLLWrappers.@declare_executable_product(llvm_cxxfilt)
JLLWrappers.@declare_executable_product(llvm_cxxmap)
JLLWrappers.@declare_executable_product(llvm_debuginfo_analyzer)
JLLWrappers.@declare_executable_product(llvm_debuginfod)
JLLWrappers.@declare_executable_product(llvm_debuginfod_find)
JLLWrappers.@declare_executable_product(llvm_diagtool)
JLLWrappers.@declare_executable_product(llvm_diff)
JLLWrappers.@declare_executable_product(llvm_dis)
JLLWrappers.@declare_executable_product(llvm_dlltool)
JLLWrappers.@declare_executable_product(llvm_dwarfdump)
JLLWrappers.@declare_executable_product(llvm_dwarfutil)
JLLWrappers.@declare_executable_product(llvm_dwp)
JLLWrappers.@declare_executable_product(llvm_extract)
JLLWrappers.@declare_executable_product(llvm_find_all_symbols)
JLLWrappers.@declare_executable_product(llvm_gsymutil)
JLLWrappers.@declare_executable_product(llvm_ifs)
JLLWrappers.@declare_executable_product(llvm_install_name_tool)
JLLWrappers.@declare_executable_product(llvm_jitlink)
JLLWrappers.@declare_executable_product(llvm_jitlink_executor)
JLLWrappers.@declare_executable_product(llvm_lib)
JLLWrappers.@declare_executable_product(llvm_libtool_darwin)
JLLWrappers.@declare_executable_product(llvm_link)
JLLWrappers.@declare_executable_product(llvm_lipo)
JLLWrappers.@declare_executable_product(llvm_lto)
JLLWrappers.@declare_executable_product(llvm_lto2)
JLLWrappers.@declare_executable_product(llvm_mc)
JLLWrappers.@declare_executable_product(llvm_mca)
JLLWrappers.@declare_executable_product(llvm_ml)
JLLWrappers.@declare_executable_product(llvm_modextract)
JLLWrappers.@declare_executable_product(llvm_modularize)
JLLWrappers.@declare_executable_product(llvm_mt)
JLLWrappers.@declare_executable_product(llvm_nm)
JLLWrappers.@declare_executable_product(llvm_not)
JLLWrappers.@declare_executable_product(llvm_nvptx_arch)
JLLWrappers.@declare_executable_product(llvm_obj2yaml)
JLLWrappers.@declare_executable_product(llvm_objcopy)
JLLWrappers.@declare_executable_product(llvm_objdump)
JLLWrappers.@declare_executable_product(llvm_opt_report)
JLLWrappers.@declare_executable_product(llvm_otool)
JLLWrappers.@declare_executable_product(llvm_pdbutil)
JLLWrappers.@declare_executable_product(llvm_pp_trace)
JLLWrappers.@declare_executable_product(llvm_profdata)
JLLWrappers.@declare_executable_product(llvm_profgen)
JLLWrappers.@declare_executable_product(llvm_ranlib)
JLLWrappers.@declare_executable_product(llvm_rc)
JLLWrappers.@declare_executable_product(llvm_readelf)
JLLWrappers.@declare_executable_product(llvm_readobj)
JLLWrappers.@declare_executable_product(llvm_readtapi)
JLLWrappers.@declare_executable_product(llvm_reduce)
JLLWrappers.@declare_executable_product(llvm_remarkutil)
JLLWrappers.@declare_executable_product(llvm_rtdyld)
JLLWrappers.@declare_executable_product(llvm_sancov)
JLLWrappers.@declare_executable_product(llvm_sanstats)
JLLWrappers.@declare_executable_product(llvm_sim)
JLLWrappers.@declare_executable_product(llvm_size)
JLLWrappers.@declare_executable_product(llvm_split)
JLLWrappers.@declare_executable_product(llvm_split_file)
JLLWrappers.@declare_executable_product(llvm_stress)
JLLWrappers.@declare_executable_product(llvm_strings)
JLLWrappers.@declare_executable_product(llvm_strip)
JLLWrappers.@declare_executable_product(llvm_symbolizer)
JLLWrappers.@declare_executable_product(llvm_tblgen)
JLLWrappers.@declare_executable_product(llvm_tli_checker)
JLLWrappers.@declare_executable_product(llvm_undname)
JLLWrappers.@declare_executable_product(llvm_verify_uselistorder)
JLLWrappers.@declare_executable_product(llvm_windres)
JLLWrappers.@declare_executable_product(llvm_xray)
JLLWrappers.@declare_executable_product(llvm_yaml2obj)
JLLWrappers.@declare_executable_product(llvm_yaml_bench)
JLLWrappers.@declare_executable_product(opt)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, libLLVM_jll)
    JLLWrappers.@init_executable_product(
        llc,
        "tools\\llc.exe",
    )

    JLLWrappers.@init_executable_product(
        lli,
        "tools\\lli.exe",
    )

    JLLWrappers.@init_executable_product(
        lli_child_target,
        "tools\\lli-child-target.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_FileCheck,
        "tools\\FileCheck.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_PerfectShuffle,
        "tools\\llvm-PerfectShuffle.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_UnicodeNameMappingGenerator,
        "tools\\UnicodeNameMappingGenerator.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_addr2line,
        "tools\\llvm-addr2line.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_amdgpu_arch,
        "tools\\amdgpu-arch.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_ar,
        "tools\\llvm-ar.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_as,
        "tools\\llvm-as.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_bcanalyzer,
        "tools\\llvm-bcanalyzer.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_bitcode_strip,
        "tools\\llvm-bitcode-strip.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_bugpoint,
        "tools\\bugpoint.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_c_test,
        "tools\\llvm-c-test.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_cat,
        "tools\\llvm-cat.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_cfi_verify,
        "tools\\llvm-cfi-verify.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_count,
        "tools\\count.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_cov,
        "tools\\llvm-cov.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_cvtres,
        "tools\\llvm-cvtres.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_cxxdump,
        "tools\\llvm-cxxdump.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_cxxfilt,
        "tools\\llvm-cxxfilt.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_cxxmap,
        "tools\\llvm-cxxmap.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_debuginfo_analyzer,
        "tools\\llvm-debuginfo-analyzer.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_debuginfod,
        "tools\\llvm-debuginfod.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_debuginfod_find,
        "tools\\llvm-debuginfod-find.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_diagtool,
        "tools\\diagtool.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_diff,
        "tools\\llvm-diff.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_dis,
        "tools\\llvm-dis.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_dlltool,
        "tools\\llvm-dlltool.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_dwarfdump,
        "tools\\llvm-dwarfdump.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_dwarfutil,
        "tools\\llvm-dwarfutil.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_dwp,
        "tools\\llvm-dwp.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_extract,
        "tools\\llvm-extract.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_find_all_symbols,
        "tools\\find-all-symbols.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_gsymutil,
        "tools\\llvm-gsymutil.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_ifs,
        "tools\\llvm-ifs.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_install_name_tool,
        "tools\\llvm-install-name-tool.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_jitlink,
        "tools\\llvm-jitlink.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_jitlink_executor,
        "tools\\llvm-jitlink-executor.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_lib,
        "tools\\llvm-lib.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_libtool_darwin,
        "tools\\llvm-libtool-darwin.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_link,
        "tools\\llvm-link.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_lipo,
        "tools\\llvm-lipo.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_lto,
        "tools\\llvm-lto.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_lto2,
        "tools\\llvm-lto2.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_mc,
        "tools\\llvm-mc.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_mca,
        "tools\\llvm-mca.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_ml,
        "tools\\llvm-ml.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_modextract,
        "tools\\llvm-modextract.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_modularize,
        "tools\\modularize.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_mt,
        "tools\\llvm-mt.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_nm,
        "tools\\llvm-nm.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_not,
        "tools\\not.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_nvptx_arch,
        "tools\\nvptx-arch.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_obj2yaml,
        "tools\\obj2yaml.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_objcopy,
        "tools\\llvm-objcopy.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_objdump,
        "tools\\llvm-objdump.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_opt_report,
        "tools\\llvm-opt-report.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_otool,
        "tools\\llvm-otool.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_pdbutil,
        "tools\\llvm-pdbutil.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_pp_trace,
        "tools\\pp-trace.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_profdata,
        "tools\\llvm-profdata.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_profgen,
        "tools\\llvm-profgen.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_ranlib,
        "tools\\llvm-ranlib.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_rc,
        "tools\\llvm-rc.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_readelf,
        "tools\\llvm-readelf.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_readobj,
        "tools\\llvm-readobj.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_readtapi,
        "tools\\llvm-readtapi.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_reduce,
        "tools\\llvm-reduce.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_remarkutil,
        "tools\\llvm-remarkutil.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_rtdyld,
        "tools\\llvm-rtdyld.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_sancov,
        "tools\\sancov.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_sanstats,
        "tools\\sanstats.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_sim,
        "tools\\llvm-sim.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_size,
        "tools\\llvm-size.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_split,
        "tools\\llvm-split.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_split_file,
        "tools\\split-file.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_stress,
        "tools\\llvm-stress.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_strings,
        "tools\\llvm-strings.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_strip,
        "tools\\llvm-strip.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_symbolizer,
        "tools\\llvm-symbolizer.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_tblgen,
        "tools\\llvm-tblgen.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_tli_checker,
        "tools\\llvm-tli-checker.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_undname,
        "tools\\llvm-undname.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_verify_uselistorder,
        "tools\\verify-uselistorder.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_windres,
        "tools\\llvm-windres.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_xray,
        "tools\\llvm-xray.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_yaml2obj,
        "tools\\yaml2obj.exe",
    )

    JLLWrappers.@init_executable_product(
        llvm_yaml_bench,
        "tools\\yaml-bench.exe",
    )

    JLLWrappers.@init_executable_product(
        opt,
        "tools\\opt.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
